services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: booking
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
